<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/* Explain Views & Controllers organization :
  
  Every Controller loads a common index.php which loads a specific
  page ( home.php , splash.php , callback.php , connect.php ...) 
  which also loads specifc components ( sign-up.php , login.php , feed.php , settings.php ... )
  among with the page specific includes ( hedaer.php , footer.php ) 
  
*/



class Init extends CI_Controller {

 /* 
  * define the page url  
  */
  private static $page_url = "/init";  
  
  
 /* 
  * define the $data that will be passed to the view  
  */
  private static $data = array();
  
  
  

  function __construct()
	{
	 
   /* 
    * load the parent construct 
    */  
    parent::__construct();
		  
   /* 
    * set the page-name & component once and for all for this controller 
    */
    $page = self::$data['page'] = new stdClass();
    $component = self::$data['component'] = new stdClass();
    
    // set base path (component name will be appended later)
    $component->path = "components/";

    $page->name = 'init';
    
    /* 
    this should probably be generated by a helper function  
    */
    $page->path = 'pages/init/';
    $page->url  = $page->path . '/page.php'; 
      
	}
  
  
  
  
  
  
  /*
   * the index() acts like a router
   * the user never stays on it so it doesn't have a view
  */
	public function index() {	
			
		if( !$this->session->userdata( 'logged_in' ) ) {
      
      /*
      if we just call the self::method instead of redirect() than the url is not gonna' be changed
      it may be usefull in some cases but for now I wanna' stick with this
      */
      
      //  load splah page
      redirect( self::$page_url . '/splash_page' );
            								
		} else {
		  
		  redirect( 'home' );
		  
		}
		
	}
	
	public function splash_page() {
  	
  	// I keep getting an error when I try to use $component - undefined
  	// spent a good 40 minuets trying to figure something global out. WTF PHP!?
  	self::$data[ 'component' ]->path .= 'splash/';
  	self::$data[ 'component' ]->name = 'splash';
  	
  	$this->load->view( 'index.php' , self::$data );
  	
	}
	
	/* Everything below this point is actually a COMPONENT */
	
	
  /*
   * SIGNUP component
  */
	public function signup() {	

		/* 
		 * check one more time if the user exists in the session and fallback to index() if NOT
		 */	
		if( $this->session->userdata( 'logged_in' ) ) { 
		  
		  //if the user is in the session then index() is gonna' redirect it wherever it needs ( home.php )
  		redirect( self::$page_url );
		
		}
    
    /* ElSE */

    /* 
     * set the component
    */
    $component = self::$data['component'] = new stdClass();
    
    /* 
     * set the component infos
     * not sure if this is the best way but is fine as long as we don't have too many components
     * I guess the best would be to have a class doing it
     */
    $component->name = 'signup';
    $component->path .= 'signup/';
    
    
    /* 
    load the helpers   
    */
	  $this->load->helper( 'form' );
	  $this->load->library( 'form_validation' );
	  
	  $this->form_validation->set_rules( 
	   
	     array(
	        array(
	              'field' => 'user_name',
	              'label' => 'User Name',
	              'rules' => 'trim|required|min_length[5]|max_length[30]|is_unique[users.user_name]'
	        ),
	        array(
	              'field' => 'email',
	              'label' => 'Email',
	              'rules' => 'trim|required|valid_email|is_unique[users.email]'
	        ),
	        array(
	              'field' => 'password',
	              'label' => 'Password',
	              'rules' => 'required|matches[password_confirm]|md5'
	        ),
	        array(
	              'field' => 'password_confirm',
	              'label' => 'Password Confirmation',
	              'rules' => 'required'
	        )
	     ) 
	     
	   );
	      
	  $this->form_validation->set_error_delimiters( '<div class="error">' , '</div>' );
	  
    		  
		var_dump( $this->form_validation->run() );
/*     exit();	   */
    
	  if( $this->form_validation->run() ) {
		  
  	  /*
		  ****TO WHO EVER READS THIS****
		  At this point the script doesn't get here. Not sure why but I'm kind of tired so I'll go home:D
		  
		  - Dude, there's only 1 other person will read this
		  */
		  
		  
		  
		  /* this should actually be stored in a model */
		  
		  $this->load->library('session');
		  
		  $email = $this->input->post( 'email' );
		  $user_name = $this->input->post( 'user_name' );
		  
		  // Enter information into database
		  $this->db->insert( 'users' , array(
		        'user_name' => $user_name,
		        'email' => $email,
		        'password' => $this->input->post( 'password' )
		      ) );
		  
		  // get the user_id from the newly created row
		  $user_id = $this->db->get_where( 'users' , array(
		        'user_name' => $user_name,
		        'email' => $email
		      ) , 1 );
		  
		  /* still need to add the user to session and send it to the home page 
  		  
  		  update: actually it should redirect it to verify login and from there redirect to wherever if it's good
		  */
		  
		  
  	 
		  //something like this
		  //but maybe stored somewhere else ( where the inserts are made )
		  
		  //if the user is in the session then index() is gonna' redirect it wherever it needs ( home.php )
  		
  		redirect( self::$page_url . "/verifylogin" );
		  
		  /*
      $this->session->set_user_data( array(
      			        'user_id' => $user_id,
      			        'logged_in' => TRUE
      			      ) );
      */
		  
		  //$data[ 'message' ] = 'Congratulations on signing up!';
		  
		}	

		$this->load->view( 'index.php' , self::$data );
	
	}
	
	
	
	/*
   * SIGNUP component
  */
	public function verifylogin() {	
  
    /* load the User model */
  	$this->load->model('User','',false);
  	
  	/* load the credential validation library */
		$this->load->library( 'form_validation' );
		
		$this->form_validation->set_rules( 'email', 'Email', 'trim|required|xss_clean' );
		$this->form_validation->set_rules( 'password', 'Password', 'trim|required|xss_clean|callback__check_password' );
		
    
    /* 
    * if it's valid populate the session with the user info and redirect to self again (this time should be re-redirected to home )
    */ 
    		
		if( $this->form_validation->run() == true ){
				
		  $user_info = User::validate_login( $password , true );
            					
			$this->session->set_userdata( 'logged_in' , $user_info );
	
		} 
  	
  	redirect( self::$page_url );
  	
	}
	
	//called by self::verifylogin();
	private function _check_password( $password ) {
  	
    return User::validate_login( $password );	
  	
	}
	
}	

/* End of file init.php */
/* Location: ./application/controllers/init.php */