// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  $(document).ready(function() {
    var getPage, global, settings_component;
    global = {
      component: {
        settings: function() {
          return settings_component();
        }
      }
    };
    getPage = function(comp) {
      if (typeof global.component[comp] === 'function') {
        return global.component[comp]();
      }
    };
    settings_component = function() {};
    return getPage($('section[component]').attr('component'));
  });

}).call(this);
